# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yibai@pku
email: mengyibai@pku.edu.cn
description: > # this means to ignore newlines until "baseurl:"
      Yibai's personal blog, where you could see all sorts of crazy stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mengyibai.cn" # the base hostname & protocol for your site
twitter_username: shit
github_username: YibaiMeng
zhihu_username: yibaiafarensis

# Build settings
markdown: kramdown
mathjax: true

# compress HTML settings
compress_html:
  clippings: []
